'use strict';

/**
 * @module dashboard/data-providers/framework-modules
 * @description 框架核心模块注册表和依赖关系定义，列出所有运行时模块及其加载路径和依赖顺序
 */

/** @constant {Array<{name: string, path: string, deprecated?: boolean, replacement?: string}>} 核心模块注册表 */
const CORE_MODULES = [
  { name: 'SkillRouter', path: '../../../runtime/skill/skill-router' },
  { name: 'SessionManager', path: '../../../runtime/session/session-manager' },
  { name: 'PhaseOrchestrator', path: '../../../runtime/workflow/phase-orchestrator' },
  { name: 'RBACEnforcer', path: '../../../permission/rbac-enforcer' },
  { name: 'PermissionGuard', path: '../../../permission/permission-guard' },
  { name: 'AuditLogger', path: '../../../permission/audit-logger' },
  { name: 'TDDGate', path: '../../../gate/tdd-gate' },
  { name: 'EvidenceVerifier', path: '../../../gate/evidence-verifier' },
  { name: 'FrameworkComplianceChecker', path: '../../../gate/framework-compliance-checker' },
  { name: 'MemoryStore', path: '../../../runtime/thought/memory-store' },
  { name: 'CheckpointManager', path: '../../../runtime/session/checkpoint-manager' },
  { name: 'SkillImprover', path: '../../../runtime/skill/skill-improver' },
  { name: 'WorkflowTemplate', path: '../../../runtime/workflow/workflow-template' },
  { name: 'DesignSkillEngine', path: '../../../gate/design-skill-engine' },
  { name: 'AgentDeployment', path: '../../../runtime/agent/agent-deployment' },
  { name: 'ChangelogArchive', path: '../../changelog-archive' },
  { name: 'WebSocketHandler', path: '../../websocket-handler' },
  { name: 'AgentRuntime', path: '../../../runtime/agent/agent-runtime' },
  { name: 'AgentLifecycleController', path: '../../../runtime/agent/agent-lifecycle-controller' },
  { name: 'AgentSandbox', path: '../../../runtime/agent/agent-sandbox' },
  { name: 'AgentMonitor', path: '../../../runtime/agent/agent-monitor' },
  { name: 'AgentStateManager', path: '../../../runtime/agent/agent-state-manager' },
  { name: 'AgentWorkflowIntegration', path: '../../../runtime/agent/agent-workflow-integration' },
  { name: 'TokenManager', path: '../../../runtime/model/token-manager' },
  { name: 'DeepeningOrchestrator', path: '../../../runtime/deepening/deepening-orchestrator' },
  { name: 'QualityScorer', path: '../../../runtime/quality/quality-scorer' },
  { name: 'DeepeningPipeline', path: '../../../runtime/deepening/deepening-pipeline' },
  { name: 'DeepeningHealthMonitor', path: '../../../runtime/deepening/deepening-health-monitor', deprecated: true, replacement: 'HealthChecker' },
  { name: 'DeepeningEventStore', path: '../../../runtime/deepening/deepening-event-store' },
  { name: 'DeepeningCache', path: '../../../runtime/deepening/deepening-cache' },
  { name: 'DeepeningErrorHandler', path: '../../../runtime/deepening/deepening-error-handler' },
  { name: 'DeepeningCircuitBreaker', path: '../../../runtime/deepening/deepening-circuit-breaker' },
  { name: 'DeepeningTaskQueue', path: '../../../runtime/deepening/deepening-task-queue' },
  { name: 'DeepeningResourceManager', path: '../../../runtime/deepening/deepening-resource-manager' },
  { name: 'DeepeningConfigManager', path: '../../../runtime/deepening/deepening-config-manager' },
  { name: 'DeepeningLockManager', path: '../../../runtime/deepening/deepening-lock-manager' },
  { name: 'DeepeningRateLimiter', path: '../../../runtime/deepening/deepening-rate-limiter' },
  { name: 'DeepeningSnapshotStore', path: '../../../runtime/deepening/deepening-snapshot-store' },
  { name: 'DeepeningConnectionPool', path: '../../../runtime/deepening/deepening-connection-pool' },
  { name: 'DeepeningTaskScheduler', path: '../../../runtime/deepening/deepening-task-scheduler' },
  { name: 'DeepeningStateManager', path: '../../../runtime/deepening/deepening-state-manager' },
  { name: 'DeepeningEventBus', path: '../../../runtime/deepening/deepening-event-bus', deprecated: true, replacement: 'EventBus' },
  { name: 'SkillReducer', path: '../../../runtime/skill/skill-reducer' },
  { name: 'GeneratorVerifier', path: '../../../gate/generator-verifier' },
  { name: 'IsolatedContextManager', path: '../../../runtime/context/isolated-context-manager' },
  { name: 'PlanPersistence', path: '../../../runtime/workflow/plan-persistence' },
  { name: 'CollaborationModeRouter', path: '../../../runtime/collaboration/collaboration-mode-router' },
  { name: 'StructuredIntent', path: '../../../runtime/user/structured-intent' },
  { name: 'SubagentExecutor', path: '../../../runtime/agent/subagent-executor' },
  { name: 'PairChat', path: '../../../runtime/collaboration/pair-chat' },
  { name: 'ChatChain', path: '../../../runtime/collaboration/chat-chain' },
  { name: 'DeepeningModuleRegistry', path: '../../../runtime/deepening/deepening-module-registry' },
  { name: 'AiCodeTrustScorer', path: '../../../runtime/quality/ai-code-trust-scorer' },
  { name: 'ComprehensionDebtTracker', path: '../../../runtime/quality/comprehension-debt-tracker' },
  { name: 'DeliveryEfficiencyMeter', path: '../../../runtime/quality/delivery-efficiency-meter' },
  { name: 'MultiAgentOrchestrator', path: '../../../runtime/agent/multi-agent-orchestrator' },
  { name: 'AgentArchitectureOrchestrator', path: '../../../runtime/infrastructure/agent-architecture-orchestrator' },
  { name: 'ContainerSandboxManager', path: '../../../runtime/infrastructure/container-sandbox-manager' },
  { name: 'TaskDecomposer', path: '../../../runtime/workflow/task-decomposer' },
  { name: 'ResultAggregator', path: '../../../runtime/collaboration/result-aggregator' },
  { name: 'RLRewardBridge', path: '../../../runtime/skill/rl-reward-bridge' },
  { name: 'ScenarioPredictor', path: '../../../runtime/causal/scenario-predictor' },
  { name: 'SimulationEngine', path: '../../../runtime/causal/simulation-engine' },
  { name: 'WorldLineManager', path: '../../../runtime/causal/world-line-manager' },
  { name: 'CausalDataBus', path: '../../../runtime/causal/causal-data-bus' },
  { name: 'CausalBufferManager', path: '../../../runtime/causal/causal-buffer-manager' },
  { name: 'CausalMemoryStore', path: '../../../runtime/causal/causal-memory-store' },
  { name: 'StructuredOutputGenerator', path: '../../../runtime/generation/structured-output-generator' },
  { name: 'CMAAdapter', path: '../../../runtime/adapter/cma-adapter' },
  { name: 'AffinityLearner', path: '../../../runtime/user/affinity-learner' },
  { name: 'DigitalTwinEngine', path: '../../../runtime/user/digital-twin-engine' },
  { name: 'CausalConsistencyChecker', path: '../../../runtime/causal/causal-consistency-checker' },
  { name: 'CausalVectorIndex', path: '../../../runtime/causal/causal-vector-index' },
  { name: 'CausalConfigValidator', path: '../../../runtime/causal/causal-config-validator' },
];

/** @constant {Array<[string, string[], boolean?]>} 模块依赖顺序表，每项为[模块名, 依赖列表, 是否废弃] */
const MODULE_DEPENDENCY_ORDER = [
  ['SkillRouter', []],
  ['SessionManager', ['SkillRouter']],
  ['PhaseOrchestrator', ['SessionManager']],
  ['RBACEnforcer', ['SkillRouter']],
  ['PermissionGuard', ['RBACEnforcer']],
  ['AuditLogger', ['RBACEnforcer']],
  ['TDDGate', []],
  ['EvidenceVerifier', ['TDDGate']],
  ['FrameworkComplianceChecker', ['TDDGate']],
  ['MemoryStore', []],
  ['CheckpointManager', ['MemoryStore']],
  ['SkillImprover', ['SkillRouter']],
  ['WorkflowTemplate', []],
  ['DesignSkillEngine', []],
  ['AgentDeployment', ['RBACEnforcer']],
  ['ChangelogArchive', []],
  ['WebSocketHandler', []],
  ['AgentRuntime', ['SessionManager']],
  ['AgentLifecycleController', ['AgentRuntime']],
  ['AgentSandbox', ['AgentRuntime']],
  ['AgentMonitor', ['AgentRuntime']],
  ['AgentStateManager', ['AgentRuntime']],
  ['AgentWorkflowIntegration', ['AgentRuntime']],
  ['TokenManager', []],
  ['DeepeningOrchestrator', []],
  ['QualityScorer', []],
  ['DeepeningPipeline', ['DeepeningOrchestrator', 'QualityScorer']],
  ['DeepeningHealthMonitor', [], true],
  ['DeepeningEventStore', []],
  ['DeepeningCache', []],
  ['DeepeningErrorHandler', []],
  ['DeepeningCircuitBreaker', []],
  ['DeepeningTaskQueue', []],
  ['DeepeningResourceManager', []],
  ['DeepeningConfigManager', []],
  ['DeepeningLockManager', []],
  ['DeepeningRateLimiter', []],
  ['DeepeningSnapshotStore', []],
  ['DeepeningConnectionPool', []],
  ['DeepeningTaskScheduler', []],
  ['DeepeningStateManager', []],
  ['DeepeningEventBus', [], true],
  ['AiCodeTrustScorer', []],
  ['ComprehensionDebtTracker', []],
  ['DeliveryEfficiencyMeter', []],
  ['MultiAgentOrchestrator', ['SessionManager', 'EventBus']],
  ['AgentArchitectureOrchestrator', ['MultiAgentOrchestrator']],
  ['ContainerSandboxManager', ['AgentArchitectureOrchestrator']],
  ['TaskDecomposer', ['MultiAgentOrchestrator']],
  ['ResultAggregator', ['MultiAgentOrchestrator']],
  ['RLRewardBridge', ['SkillRouter']],
  ['ScenarioPredictor', ['CausalDataBus']],
  ['SimulationEngine', ['CausalDataBus', 'ScenarioPredictor']],
  ['WorldLineManager', ['CausalDataBus']],
  ['CausalDataBus', ['EventBus']],
  ['CausalBufferManager', ['CausalDataBus']],
  ['CausalMemoryStore', ['CausalDataBus']],
  ['StructuredOutputGenerator', ['TokenManager']],
  ['CMAAdapter', ['TokenManager']],
  ['AffinityLearner', ['SessionManager']],
  ['DigitalTwinEngine', ['AffinityLearner']],
  ['CausalConsistencyChecker', ['CausalDataBus']],
  ['CausalVectorIndex', ['CausalDataBus']],
  ['CausalConfigValidator', ['CausalDataBus']],
];

/** @constant {number} 预期运行时模块总数 */
const EXPECTED_RUNTIME_MODULE_COUNT = 52;

module.exports = { CORE_MODULES, MODULE_DEPENDENCY_ORDER, EXPECTED_RUNTIME_MODULE_COUNT };
