'use strict';

/**
 * @module dashboard/constants/static-data
 * @description Dashboard静态展示数据模块，定义架构信息、框架特性、全景元数据等前端展示用的静态数据结构
 */

/** @constant {object} 架构展示数据，包含核心原则、运行时模块、权限模块、门禁模块和流程图 */
const ARCHITECTURE_DATA = {
  corePrinciples: [
    { icon: '🏗️', title: '分层分责', desc: '6个Agent角色各司其职，Team Lead负责调度，Analyst负责设计，Worker负责实现，QA负责质量' },
    { icon: '📄', title: '文档驱动', desc: 'Markdown+YAML Frontmatter自描述配置，既是文档也是可解析的规则定义' },
    { icon: '🔒', title: '流程管控', desc: '六阶段强制流程编排，TDD门禁检查，证据验证机制确保质量' },
    { icon: '🔄', title: '容错自愈', desc: '检查点恢复、指数退避重试、三级升级策略、对抗审查机制' },
  ],
  runtimeModules: [
    { name: 'SkillRouter', desc: '技能发现与路由', color: 'var(--primary-light)' },
    { name: 'SessionManager', desc: '会话状态管理', color: 'var(--purple)' },
    { name: 'PhaseOrchestrator', desc: '六阶段流程编排', color: 'var(--cyan)' },
    { name: 'EventBus', desc: '事件总线与中间件', color: 'var(--success)' },
    { name: 'MemoryStore', desc: '知识与摘要存储', color: 'var(--warning)' },
    { name: 'AgentChannel', desc: 'Agent间通信通道', color: 'var(--danger)' },
    { name: 'WorkflowDAG', desc: 'DAG工作流引擎', color: 'var(--primary-light)' },
    { name: 'CheckpointManager', desc: '检查点管理', color: 'var(--purple)' },
    { name: 'RetryEngine', desc: '重试与升级策略', color: 'var(--cyan)' },
    { name: 'ConcurrencyController', desc: '并发控制信号量', color: 'var(--success)' },
    { name: 'AdversarialReview', desc: '对抗审查', color: 'var(--warning)' },
    { name: 'SkillImprover', desc: '技能经验学习', color: 'var(--danger)' },
    { name: 'PlatformCoordinator', desc: '跨平台协调', color: 'var(--primary-light)' },
    { name: 'WorkflowTemplate', desc: '工作流模板', color: 'var(--purple)' },
    { name: 'PluginManager', desc: '插件管理', color: 'var(--cyan)' },
    { name: 'HealthChecker', desc: '健康检查', color: 'var(--success)' },
    { name: 'MultiAgentOrchestrator', desc: '多智能体协调控制器', color: 'var(--primary-light)' },
    { name: 'AgentArchitectureOrchestrator', desc: 'Agent工程化架构协调器', color: 'var(--purple)' },
    { name: 'ContainerSandboxManager', desc: '容器沙箱管理器', color: 'var(--cyan)' },
    { name: 'TaskDecomposer', desc: '任务自动分解器', color: 'var(--success)' },
    { name: 'ResultAggregator', desc: '多Agent结果聚合器', color: 'var(--warning)' },
  ],
  permModules: [
    { name: 'RBACEnforcer', desc: '基于角色的访问控制，加载agents/和skills/权限定义，验证执行权限', color: 'var(--danger)' },
    { name: 'PermissionGuard', desc: '文件操作守卫，路径遍历防护、危险命令检测、文件级锁', color: 'var(--warning)' },
    { name: 'AuditLogger', desc: '审计日志记录，BoundedArray存储、防抖持久化、过滤查询', color: 'var(--primary-light)' },
  ],
  permSecurityCapabilities: [
    { name: '路径遍历防护', status: '✓ 阻止项目外文件操作' },
    { name: '危险命令检测', status: '✓ 14种危险模式匹配' },
    { name: '文件级锁', status: '✓ 5分钟超时自动释放' },
    { name: 'Session ID验证', status: '✓ 格式+时序安全比较' },
    { name: 'RBAC三级执行', status: 'strict / recommended / optional' },
  ],
  gateModules: [
    { name: 'TDDGate', desc: 'TDD强制门禁，RED-GREEN-REFACTOR阶段检测，覆盖率阈值验证', color: 'var(--purple)' },
    { name: 'EvidenceVerifier', desc: '证据验证器，为每种Skill定义所需证据类型，验证完成声明', color: 'var(--danger)' },
    { name: 'FrameworkComplianceChecker', desc: '框架合规检查，6类规则（命名/结构/安全/持久化/API/错误）', color: 'var(--primary-light)' },
    { name: 'DeviationApproval', desc: '偏离审批管理，TTL过期机制，请求/批准/拒绝/撤销流程', color: 'var(--warning)' },
    { name: 'CodeReviewFrameworkCheck', desc: '代码审查框架检查，8类自动+手动检查项，生成verdict', color: 'var(--success)' },
  ],
  initFlow: [
    { step: '1. validateConfig()', desc: '验证项目配置完整性' },
    { step: '2. SkillRouter.discover()', desc: '扫描.harness/skills/解析Frontmatter' },
    { step: '3. SessionManager._restore()', desc: '从.harness/sessions/恢复会话' },
    { step: '4. RBACEnforcer.load()', desc: '加载agents/和skills/权限定义' },
    { step: '5. EventBus + PluginManager', desc: '事件总线初始化与插件注册' },
    { step: '6. MemoryStore + CheckpointManager', desc: '知识存储与检查点管理初始化' },
  ],
  eventFlow: [
    { event: 'session:created', flow: 'SessionManager → EventBus → 外部监听' },
    { event: 'session:phase-change', flow: 'SessionManager → EventBus → CheckpointManager' },
    { event: 'session:skill-complete', flow: 'SessionManager → EventBus → SkillImprover' },
    { event: 'session:budget-warning', flow: 'SessionManager → EventBus → 外部监听' },
    { event: 'session:shutdown', flow: 'SessionManager → EventBus → MemoryStore.saveSessionSummary' },
  ],
  apiDataFlow: [
    { step: 'DataLayer.fetchAll()', desc: '14个API端点并行获取数据' },
    { step: 'Store.batchUpdate()', desc: '批量更新状态 + 变更检测哈希' },
    { step: 'Store._notify()', desc: '仅通知变更的key对应订阅者' },
    { step: 'Renderers.*()', desc: '按需渲染对应面板组件' },
  ],
  persistenceMap: [
    { module: 'SessionManager', path: '.harness/sessions/{id}.json', strategy: '单文件+防抖200ms' },
    { module: 'CheckpointManager', path: '.harness/checkpoints/{id}.json', strategy: '原子写入.tmp+rename' },
    { module: 'MemoryStore', path: '.harness/knowledge/knowledge.json', strategy: '全量+防抖500ms' },
    { module: 'SkillImprover', path: '.harness/skills-learned/learnings.json', strategy: '全量+防抖' },
    { module: 'AuditLogger', path: '.harness/audit/audit-log.json', strategy: '全量+防抖500ms' },
    { module: 'WorkflowTemplate', path: '.harness/workflow-templates/templates.json', strategy: '全量+防抖' },
    { module: 'DeviationApproval', path: '.harness/deviations/deviations.json', strategy: '原子写入.tmp+rename' },
    { module: 'CodeReviewFrameworkCheck', path: '.harness/reviews/reviews.json', strategy: '原子写入.tmp+rename' },
    { module: 'ChangelogArchive', path: '.harness/archive/{id}.json', strategy: 'SHA256完整性校验' },
  ],
};

/** @constant {object} 框架特性数据，包含重试策略、DAG引擎、安全能力、并发控制、TDD门禁和协作模式 */
const FRAMEWORK_FEATURES_DATA = {
  retry: {
    escalationStrategies: [
      { name: 'Replan 重新规划', desc: '调整任务参数后重试' },
      { name: 'Decompose 分解', desc: '拆分为子任务并行执行（最大深度3）' },
      { name: 'Escalate 上报', desc: '通知上级Agent介入处理' },
    ],
    maxBackoff: '60s',
  },
  dag: {
    features: [
      { name: 'DAG引擎', status: '✓ 环检测+拓扑排序' },
      { name: '自环检测', status: '✓ 拒绝' },
    ],
  },
  security: {
    capabilities: [
      { name: '路径遍历防护', status: '✓ 启用' },
      { name: '危险命令检测', status: '✓ 启用' },
      { name: '文件级锁', status: '✓ 5分钟超时' },
      { name: '时序安全比较', status: '✓ timingSafeEqual' },
    ],
  },
  concurrency: {
    maxConcurrency: 6,
    queueLimit: 100,
    communication: '发布/订阅',
    channels: [
      { name: 'AgentChannel', desc: '跨Agent结果共享与事件通知' },
      { name: 'EventBus', desc: '中间件+历史记录+异步等待' },
      { name: 'PlatformCoordinator', desc: '跨平台并行广播+路由环路检测' },
    ],
  },
  tdd: {
    evidenceTypes: [
      { key: 'test_output', desc: '测试输出（必须非空）' },
      { key: 'coverage_report', desc: '覆盖率报告' },
      { key: 'code_diff', desc: '代码差异' },
    ],
    phases: [
      { emoji: '🔴', name: 'RED — 先写失败测试' },
      { emoji: '🟢', name: 'GREEN — 最小实现通过' },
      { emoji: '🔵', name: 'REFACTOR — 重构优化' },
    ],
  },
  checkpoint: {
    atomicWrite: '✓ .tmp+rename',
    recovery: '✓ 支持',
  },
  collaboration: {
    pipeline: [
      { name: 'StructuredIntent', label: '意图解析', desc: '解析用户消息为结构化意图' },
      { name: 'SkillRouter', label: '技能路由', desc: 'L1轻量匹配→L2按需加载' },
      { name: 'CollaborationModeRouter', label: '模式选择', desc: '根据任务特征选择协作模式' },
      { name: 'SubagentExecutor', label: '子智能体执行', desc: '派生独立Subagent并行执行' },
      { name: 'GeneratorVerifier', label: '质量验证', desc: '验证输出质量→反馈迭代' },
      { name: 'AgentChannel', label: '结果汇总', desc: 'P2P通信→投票→融合输出' },
    ],
    defaultModes: [
      { name: 'orchestrator-subagent', icon: '🎯', desc: '任务拆解→并行执行→结果汇总', color: 'primary', useCase: '多模块并行开发' },
      { name: 'generator-verifier', icon: '✅', desc: '生成→验证→反馈→迭代优化', color: 'success', useCase: '代码审查/报告校验' },
      { name: 'agent-teams', icon: '👥', desc: '直接通信→协调→投票决策', color: 'warning', useCase: '复杂协调任务' },
      { name: 'message-bus', icon: '📡', desc: '事件驱动→发布订阅→动态接入', color: 'info', useCase: '模块解耦扩展' },
      { name: 'shared-state', icon: '🔒', desc: '乐观锁→版本控制→实时协作', color: 'purple', useCase: '多源数据同步' },
    ],
  },
  multiAgent: {
    controlMechanisms: [
      { name: '流程控制', status: '✓ 状态机+最大迭代(5)+熔断器' },
      { name: 'Token控制', status: '✓ 分层上下文+结构化摘要+预算告警' },
      { name: '完成标准(DoD)', status: '✓ 四类终止条件+量化标准' },
    ],
    terminationReasons: ['DOD_MET', 'BUDGET_EXHAUSTED', 'NO_PROGRESS', 'BOUNDARY_EXCEEDED', 'MAX_ITERATIONS', 'CIRCUIT_OPEN', 'ERROR'],
  },
  agentArchitecture: {
    pillars: [
      { name: '渐进式披露', desc: '按任务优先级分层暴露上下文' },
      { name: 'Prompt+硬编码+Linter', desc: '柔性建议+刚性约束+实时校验' },
      { name: '自验证循环', desc: 'pre-verify→execute→post-verify→retry' },
      { name: '上下文隔离', desc: 'per-Agent记忆命名空间+访问控制' },
      { name: '熵治理', desc: '4维熵值量化+跨模块协调清理' },
      { name: '可拆卸性', desc: 'register/unregister+能力声明+热替换' },
    ],
  },
  deerflow: {
    capabilities: [
      { name: '任务调度与拆解', status: '✓ 4种策略(顺序/并行/混合/管道)' },
      { name: '安全隔离与审计', status: '✓ 3级隔离(进程/容器/Worktree)' },
      { name: '结果聚合', status: '✓ 5种策略(投票/融合/摘要/层级/择优)' },
      { name: '跨会话记忆', status: '✓ 亲和度学习+数字孪生' },
      { name: '模型兼容性', status: '✓ 多模型适配+成本感知路由' },
    ],
  },
};

/** @constant {object} 全景元数据，包含节点颜色、描述、模块分类和Agent能力评分 */
const PANORAMA_METADATA = {
  nodeColors: {
    core: '#818cf8', runtime: '#a78bfa', permission: '#f87171',
    gate: '#fbbf24', agent: '#34d399', skill: '#22d3ee',
    phase: '#c084fc', infra: '#fb923c', session: '#f472b6',
    causal: '#60a5fa', deepening: '#c084fc', web: '#2dd4bf',
    thought: '#f9a8d4', agentRuntime: '#6ee7b7', collaboration: '#fbbf24',
    skillMgmt: '#22d3ee', reasoning: '#e879f9',
    multiAgent: '#818cf8', architecture: '#a78bfa', deerflow: '#34d399', generation: '#fbbf24', adapter: '#fb923c',
  },
  nodeDescs: {
    framework: '框架核心引擎，协调所有子系统运行',
    SkillRouter: '技能自动发现、匹配与路由',
    SessionManager: '会话生命周期与状态管理',
    PhaseOrchestrator: '六阶段流程编排与转换控制',
    EventBus: '事件总线，支持中间件和异步订阅',
    MemoryStore: '项目知识存储与摘要管理',
    AgentChannel: 'Agent间通信通道与共享KV',
    WorkflowDAG: 'DAG工作流引擎，拓扑排序与环检测',
    CheckpointManager: '检查点创建、恢复与持久化',
    RetryEngine: '指数退避重试与三级升级策略',
    ConcurrencyController: '并发信号量控制与排队',
    AdversarialReview: '对抗审查，双审查者共识机制',
    SkillImprover: '技能经验学习与自我改进',
    PlatformCoordinator: '跨平台消息路由与广播',
    WorkflowTemplate: '工作流模板创建与实例化',
    PluginManager: '插件注册、Hook执行与生命周期',
    HealthChecker: '健康检查注册与状态监控',
    TokenManager: 'Token预算管理与三层计数',
    DeepeningModuleRegistry: '深化模块注册与发现',
    SkillReducer: '技能精简与去重',
    CommandRouter: '斜杠命令路由与模糊匹配',
    ProgrammableHookExecutor: '可编程钩子执行器',
    ContextCompressionEngine: '上下文压缩引擎',
    GoalExecutor: '目标执行器，自主迭代收敛',
    PhaseContextInjector: '阶段上下文注入器',
    HookHandlers: '内置Hook处理器与速率限制',
    AutoregressiveContextSchema: '自回归上下文模式与版本兼容',
    CausalBufferManager: '因果缓冲区管理与注意力衰减',
    CausalMemoryStore: '因果记忆存储与检索',
    CausalVectorIndex: '因果向量索引',
    CausalConsistencyChecker: '因果一致性校验',
    ConfigCausalValidator: '配置因果验证器',
    DocFreshnessGuard: '文档新鲜度守卫',
    SelfEvolutionGovernor: '自演化治理器',
    SelfReflection: '自反思引擎',
    SignalPersistence: '信号持久化',
    PriorityQueue: '优先级队列',
    HumanApprovalGate: '人工审批门禁',
    AgentRuntime: 'Agent运行时环境',
    AgentLifecycleController: 'Agent生命周期控制器',
    AgentSandbox: 'Agent沙箱隔离',
    AgentMonitor: 'Agent监控与指标采集',
    AgentDeployment: 'Agent部署管理',
    AgentStateManager: 'Agent状态管理',
    AgentWorkflowIntegration: 'Agent工作流集成',
    AgentPackManager: 'Agent包管理',
    IsolatedContextManager: '隔离上下文管理器',
    PlanPersistence: '计划持久化',
    CollaborationModeRouter: '协作模式路由(solo/pair/chain/ensemble)',
    StructuredIntent: '结构化意图解析',
    SubagentExecutor: '子Agent执行器',
    PairChat: '结对对话',
    ChatChain: '链式对话',
    SqliteStore: 'SQLite持久化存储',
    SkillImprovementLoop: '技能改进循环',
    MemoryNudge: '记忆提醒与关联',
    SkillCreationEngine: '技能创建引擎',
    SkillCurator: '技能策展与优化',
    UserModelManager: '用户模型管理',
    MCPClient: 'MCP协议客户端(stdio/HTTP)',
    AutoVersionTracker: '自动版本追踪',
    ThoughtExtractor: '思维提取器',
    ThoughtDeduplicator: '思维去重器',
    ThoughtMemoryStore: '思维记忆存储',
    ThoughtRetrieverCycle: '思维检索循环',
    EmbeddingService: '嵌入向量服务',
    ModelSelector: '模型选择器',
    DeepeningOrchestrator: '深化推理编排器',
    DeepeningPipeline: '深化管道(21子模块)',
    DeepeningHealthMonitor: '深化健康监控',
    DeepeningCache: '深化缓存',
    DeepeningCircuitBreaker: '深化熔断器',
    DeepeningRateLimiter: '深化限流器',
    DeepeningConnectionPool: '深化连接池',
    DeepeningLoadBalancer: '深化负载均衡',
    DeepeningServiceRegistry: '深化服务注册',
    DeepeningFeatureFlags: '深化特性标志',
    DeepeningGracefulShutdown: '深化优雅关停',
    DeepeningStateManager: '深化状态管理',
    DeepeningSnapshot: '深化快照',
    DeepeningMetricsAggregator: '深化指标聚合',
    DeepeningSecurityGuard: '深化安全守卫',
    DeepeningConfigManager: '深化配置管理',
    DeepeningDeployment: '深化部署管理',
    DeepeningValidator: '深化验证器',
    DeepeningTimeoutManager: '深化超时管理',
    DeepeningRetryPolicy: '深化重试策略',
    DeepeningNotifier: '深化通知器',
    DeepeningBackpressureManager: '深化背压管理',
    DeepeningBenchmark: '深化基准测试',
    DeepeningReportGenerator: '深化报告生成',
    DeepeningStrategyPlugin: '深化策略插件',
    DeepeningTaskScheduler: '深化任务调度',
    DeepeningPluginSystem: '深化插件系统',
    DeepeningLockManager: '深化锁管理',
    DeepeningThrottle: '深化节流',
    DeepeningTaskQueue: '深化任务队列',
    DeepeningPriorityQueue: '深化优先队列',
    DeepeningResourceManager: '深化资源管理',
    DeepeningDataPipeline: '深化数据管道',
    DeepeningErrorHandler: '深化错误处理',
    DeepeningEventBus: '深化事件总线',
    DeepeningEventStore: '深化事件存储',
    DeepeningEventReplay: '深化事件回放',
    DeepeningDependencyResolver: '深化依赖解析',
    DeepeningWorkflowTemplate: '深化工作流模板',
    DeepeningAuditTrail: '深化审计追踪',
    DeepeningStateMachine: '深化状态机',
    DeepeningVisualizer: '深化可视化',
    DeepeningSnapshotStore: '深化快照存储',
    DeepeningMetricsCollector: '深化指标采集',
    RecurrentDeepeningScheduler: '循环深化调度器',
    AdaptiveDepthController: '自适应深度控制器',
    LTIContextInjector: 'LTI上下文注入器',
    MultiAgentRouter: '多Agent路由器',
    OutputFusion: '输出融合器',
    IterativeRefinement: '迭代精化器',
    ProgressiveDeepening: '渐进深化器',
    QualityScorer: '质量评分器',
    TokenAwareDeepening: 'Token感知深化',
    AffinityLearner: '亲和度学习器',
    ConvergenceDetector: '收敛检测器',
    SharedInfrastructure: '共享基础设施(连接池/负载均衡/服务注册/特性标志)',
    MultiAgentOrchestrator: '多智能体协调控制器(流程控制/Token控制/DoD)',
    AgentArchitectureOrchestrator: 'Agent工程化架构(6大架构协调)',
    ContainerSandboxManager: '容器沙箱管理(Docker隔离/审计/资源限制)',
    TaskDecomposer: '任务自动分解(关键词+LLM/4种策略/依赖图)',
    ResultAggregator: '多Agent结果聚合(5种策略/质量评估)',
    RLRewardBridge: '强化学习奖励桥接(经验回放/动作选择)',
    ScenarioPredictor: '场景预测器(蒙特卡洛/假设分析)',
    SimulationEngine: '仿真引擎(前向/后向预测)',
    WorldLineManager: '世界线管理(分支/合并/回溯)',
    StructuredOutputGenerator: '结构化输出生成(模板+验证)',
    CMAAdapter: 'CMA模型适配器(跨模型桥接)',
    DigitalTwinEngine: '数字孪生引擎(用户行为建模)',
    RBACEnforcer: '基于角色的访问控制执行',
    PermissionGuard: '文件操作守卫与路径遍历防护',
    AuditLogger: '审计日志记录与过滤查询',
    TDDGate: 'TDD强制门禁，RED-GREEN-REFACTOR检测',
    EvidenceVerifier: '完成声明证据验证器',
    FrameworkComplianceChecker: '框架合规6类规则检查',
    DeviationApproval: '偏离审批管理，TTL过期机制',
    CodeReviewFrameworkCheck: '代码审查8类检查项',
    DesignSkillEngine: '设计技能引擎，反模式检测',
    GeneratorVerifier: '生成器验证器，5维度评估',
    SkillPatchApproval: '技能补丁审批',
    DashboardServer: 'Web控制台服务器',
    WebSocketHandler: 'WebSocket实时通信',
    ChangelogArchive: '变更日志存档',
  },
  runtimeModules: ['SkillRouter', 'SessionManager', 'PhaseOrchestrator', 'EventBus', 'MemoryStore', 'AgentChannel', 'WorkflowDAG', 'CheckpointManager', 'RetryEngine', 'ConcurrencyController', 'AdversarialReview', 'SkillImprover', 'PlatformCoordinator', 'WorkflowTemplate', 'PluginManager', 'HealthChecker', 'TokenManager', 'DeepeningModuleRegistry', 'SkillReducer', 'CommandRouter', 'ProgrammableHookExecutor', 'ContextCompressionEngine', 'GoalExecutor', 'PhaseContextInjector', 'HookHandlers', 'AutoregressiveContextSchema'],
  causalModules: ['CausalDataBus', 'CausalBufferManager', 'CausalMemoryStore', 'CausalVectorIndex', 'CausalConsistencyChecker', 'ConfigCausalValidator', 'DocFreshnessGuard', 'SelfEvolutionGovernor', 'SelfReflection', 'SignalPersistence', 'PriorityQueue', 'HumanApprovalGate'],
  agentRuntimeModules: ['AgentRuntime', 'AgentLifecycleController', 'AgentSandbox', 'AgentMonitor', 'AgentDeployment', 'AgentStateManager', 'AgentWorkflowIntegration', 'AgentPackManager', 'IsolatedContextManager'],
  collaborationModules: ['PlanPersistence', 'CollaborationModeRouter', 'StructuredIntent', 'SubagentExecutor', 'PairChat', 'ChatChain', 'SqliteStore'],
  skillModules: ['SkillImprovementLoop', 'MemoryNudge', 'SkillCreationEngine', 'SkillCurator', 'UserModelManager', 'MCPClient', 'AutoVersionTracker'],
  thoughtModules: ['ThoughtExtractor', 'ThoughtDeduplicator', 'ThoughtMemoryStore', 'ThoughtRetrieverCycle', 'EmbeddingService', 'ModelSelector'],
  deepeningModules: ['DeepeningOrchestrator', 'DeepeningPipeline', 'DeepeningHealthMonitor', 'DeepeningCache', 'DeepeningCircuitBreaker', 'DeepeningRateLimiter', 'DeepeningConnectionPool', 'DeepeningLoadBalancer', 'DeepeningServiceRegistry', 'DeepeningFeatureFlags', 'DeepeningGracefulShutdown', 'DeepeningStateManager', 'DeepeningSnapshot', 'DeepeningMetricsAggregator', 'DeepeningSecurityGuard', 'DeepeningConfigManager', 'DeepeningDeployment', 'DeepeningValidator', 'DeepeningTimeoutManager', 'DeepeningRetryPolicy', 'DeepeningNotifier', 'DeepeningBackpressureManager', 'DeepeningBenchmark', 'DeepeningReportGenerator', 'DeepeningStrategyPlugin', 'DeepeningTaskScheduler', 'DeepeningPluginSystem', 'DeepeningLockManager', 'DeepeningThrottle', 'DeepeningTaskQueue', 'DeepeningPriorityQueue', 'DeepeningResourceManager', 'DeepeningDataPipeline', 'DeepeningErrorHandler', 'DeepeningEventBus', 'DeepeningEventStore', 'DeepeningEventReplay', 'DeepeningDependencyResolver', 'DeepeningWorkflowTemplate', 'DeepeningAuditTrail', 'DeepeningStateMachine', 'DeepeningVisualizer', 'DeepeningSnapshotStore', 'DeepeningMetricsCollector'],
  reasoningModules: ['RecurrentDeepeningScheduler', 'AdaptiveDepthController', 'LTIContextInjector', 'MultiAgentRouter', 'OutputFusion', 'IterativeRefinement', 'ProgressiveDeepening', 'QualityScorer', 'TokenAwareDeepening', 'AffinityLearner', 'ConvergenceDetector', 'SharedInfrastructure'],
  permModules: ['RBACEnforcer', 'PermissionGuard', 'AuditLogger'],
  gateModules: ['TDDGate', 'EvidenceVerifier', 'FrameworkComplianceChecker', 'DeviationApproval', 'CodeReviewFrameworkCheck', 'DesignSkillEngine', 'GeneratorVerifier', 'SkillPatchApproval'],
  multiAgentModules: ['MultiAgentOrchestrator', 'AgentArchitectureOrchestrator', 'ContainerSandboxManager', 'TaskDecomposer', 'ResultAggregator'],
  causalAdvModules: ['RLRewardBridge', 'ScenarioPredictor', 'SimulationEngine', 'WorldLineManager'],
  generationModules: ['StructuredOutputGenerator'],
  adapterModules: ['CMAAdapter'],
  userModules: ['AffinityLearner', 'DigitalTwinEngine'],
  webModules: ['DashboardServer', 'WebSocketHandler', 'ChangelogArchive'],
  phaseNames: ['需求探索', '需求分析', '架构设计', '模块开发', '集成测试', '部署上线'],
  agentCapabilities: {
    dimensions: ['调度', '设计', '实现', '测试', '运维', '文档'],
    scores: {
      'team-lead': [10, 7, 3, 5, 6, 7],
      'domain-analyst': [6, 10, 4, 8, 3, 8],
      'task-worker': [4, 3, 10, 4, 3, 5],
      'quality-assurance': [5, 6, 4, 10, 4, 6],
      'devops-engineer': [5, 2, 3, 4, 10, 4],
      'technical-writer': [3, 4, 2, 3, 3, 10],
      'code-reviewer': [4, 5, 8, 7, 2, 4],
      'security-reviewer': [3, 4, 5, 6, 8, 3],
      'build-error-solver': [3, 2, 7, 3, 9, 2],
      'planner': [8, 9, 2, 5, 3, 6],
      'test-writer': [4, 3, 6, 10, 2, 4],
      'typescript-reviewer': [3, 4, 9, 7, 2, 3],
      'python-reviewer': [3, 4, 9, 7, 2, 3],
      'go-reviewer': [3, 4, 9, 7, 2, 3],
      'rust-reviewer': [3, 4, 9, 7, 3, 3],
      'java-reviewer': [3, 4, 9, 7, 2, 3],
    },
  },
};

module.exports = { ARCHITECTURE_DATA, FRAMEWORK_FEATURES_DATA, PANORAMA_METADATA };
